"""create interview summaries table

Revision ID: d411eb9c7f21
Revises: 8e2f4e427fb6
Create Date: 2026-06-26 21:43:21.319149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd411eb9c7f21'
down_revision: Union[str, Sequence[str], None] = '8e2f4e427fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_feedback', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_summaries_interview_session_id'), 'interview_summaries', ['interview_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_summaries_interview_session_id'), table_name='interview_summaries')
    op.drop_table('interview_summaries')
    # ### end Alembic commands ###
